map_type: costmap

# if set to n it implies that if the obstacle detected by a laser sensor is within n meters from the base of the robot,
# that obstacle will be added to the costmap.
obstacle_range: 4.5 # worked best

# Determines the range to which we will raytrace freespace given a sensor reading ie robot will attempt to clear out 
# space in front of it up to the provided distance (in meters) away given a sensor reading. 
# More the value, more the robot will act reserved to the obstacles in the costmap
raytrace_range: 0.9 # worked best 

# The inflation radius should be set to the maximum distance from obstacles at which a cost should be incurred.
# inflation_radius: 0.25
inflation_radius: 0.27 # worked best

# the maximum tolerance to unresponsive transform updates on /tf 
transform_tolerance: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
